-- =============================================================================
-- MindMap — Initial Migration
-- =============================================================================
-- Covers:
--   • All tables with constraints and cascade deletes
--   • Indexes
--   • Security-definer helper functions (approval gate, membership, role check)
--   • Triggers: updated_at, new-user bootstrap, profile delete cleanup,
--               single-DM enforcement, workspace type immutability
--   • Invite redemption (security-definer function)
--   • RLS enabled on all tables with full policy set
--   • Supabase Storage bucket + object policies
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
-- uuid-ossp is intentionally omitted: gen_random_uuid() is built-in on
-- Postgres 13+ and is the preferred default on Supabase.
create extension if not exists "pg_trgm"; -- future full-text / trigram search


-- =============================================================================
-- TABLES
-- =============================================================================

-- profiles ----------------------------------------------------------------
-- Mirrors auth.users with app-level fields. Approval gates all data access.
create table public.profiles (
  id          uuid        primary key references auth.users(id) on delete cascade,
  email       text        not null,
  full_name   text,
  approved    boolean     not null default false,
  created_at  timestamptz not null default now()
);

comment on column public.profiles.approved is
  'Set to true by admin only. False blocks all RLS policies for the user.';


-- workspaces --------------------------------------------------------------
-- owner_id is nullable so campaign workspaces survive user deletion.
create table public.workspaces (
  id          uuid        primary key default gen_random_uuid(),
  owner_id    uuid        references public.profiles(id) on delete set null,
  type        text        not null check (type in ('personal', 'campaign')),
  name        text        not null,
  created_at  timestamptz not null default now()
);


-- workspace_members -------------------------------------------------------
create table public.workspace_members (
  workspace_id  uuid        not null references public.workspaces(id) on delete cascade,
  user_id       uuid        not null references public.profiles(id)   on delete cascade,
  role          text        not null check (role in ('owner', 'dm', 'player')),
  joined_at     timestamptz not null default now(),
  primary key (workspace_id, user_id)
);


-- notes -------------------------------------------------------------------
-- body column stores the Markdown serialization (persistence format).
-- Yjs operates on the in-memory TipTap document; Markdown is only written
-- on snapshot flush.
-- user_id nullable so notes survive profile deletion (campaign context).
create table public.notes (
  id            uuid        primary key default gen_random_uuid(),
  workspace_id  uuid        not null references public.workspaces(id) on delete cascade,
  user_id       uuid        references public.profiles(id) on delete set null,
  title         text        not null default 'Untitled',
  body          text        not null default '',
  dm_only       boolean     not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);


-- note_links --------------------------------------------------------------
-- Directional edges written by the [[Wikilink]] TipTap extension.
create table public.note_links (
  id         uuid primary key default gen_random_uuid(),
  source_id  uuid not null references public.notes(id) on delete cascade,
  target_id  uuid not null references public.notes(id) on delete cascade,
  unique (source_id, target_id)
);


-- tags --------------------------------------------------------------------
create table public.tags (
  id       uuid primary key default gen_random_uuid(),
  note_id  uuid not null references public.notes(id) on delete cascade,
  name     text not null,
  unique (note_id, name)
);


-- invites -----------------------------------------------------------------
-- Token-based invite links generated by workspace owner/dm.
-- used_at = null  →  still valid.
create table public.invites (
  id            uuid        primary key default gen_random_uuid(),
  workspace_id  uuid        not null references public.workspaces(id) on delete cascade,
  token         uuid        not null unique default gen_random_uuid(),
  created_by    uuid        not null references public.profiles(id) on delete cascade,
  expires_at    timestamptz not null,
  used_at       timestamptz,
  created_at    timestamptz not null default now()
);


-- =============================================================================
-- INDEXES
-- =============================================================================

create index idx_profiles_approved           on public.profiles(approved);

create index idx_workspaces_owner_id         on public.workspaces(owner_id);
create index idx_workspaces_type             on public.workspaces(type);

create index idx_workspace_members_user_id   on public.workspace_members(user_id);
create index idx_workspace_members_ws_id     on public.workspace_members(workspace_id);

create index idx_notes_workspace_id          on public.notes(workspace_id);
create index idx_notes_user_id               on public.notes(user_id);
create index idx_notes_updated_at            on public.notes(updated_at desc);
create index idx_notes_dm_only               on public.notes(dm_only);
-- full-text search (title + body) via pg_trgm
create index idx_notes_title_trgm            on public.notes using gin (title gin_trgm_ops);

create index idx_note_links_source_id        on public.note_links(source_id);
create index idx_note_links_target_id        on public.note_links(target_id);

create index idx_tags_note_id                on public.tags(note_id);
create index idx_tags_name                   on public.tags(name);

create index idx_invites_workspace_id        on public.invites(workspace_id);
-- partial index for pending (unredeemed) invites — most common query
create index idx_invites_pending             on public.invites(workspace_id, expires_at)
  where used_at is null;


-- =============================================================================
-- SECURITY-DEFINER HELPER FUNCTIONS
-- =============================================================================
-- Using security definer breaks potential RLS recursion: these functions read
-- tables directly, bypassing RLS, so they are safe to call from within
-- RLS policy expressions.

-- is_approved -----------------------------------------------------------------
create or replace function public.is_approved()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select coalesce(
    (select approved from public.profiles where id = auth.uid()),
    false
  );
$$;


-- is_workspace_member ---------------------------------------------------------
create or replace function public.is_workspace_member(p_workspace_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.workspace_members
    where workspace_id = p_workspace_id
      and user_id = auth.uid()
  );
$$;


-- workspace_role --------------------------------------------------------------
-- Returns current user's role in the workspace, or NULL if not a member.
create or replace function public.workspace_role(p_workspace_id uuid)
returns text
language sql
security definer
stable
set search_path = public
as $$
  select role
  from public.workspace_members
  where workspace_id = p_workspace_id
    and user_id = auth.uid();
$$;


-- =============================================================================
-- TRIGGERS
-- =============================================================================

-- updated_at auto-maintenance ------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger notes_set_updated_at
  before update on public.notes
  for each row execute function public.set_updated_at();


-- New auth user bootstrap ----------------------------------------------------
-- After a row is inserted into auth.users, atomically create:
--   1. profiles row (approved = false)
--   2. personal workspace
--   3. owner membership for that workspace
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workspace_id uuid;
  v_full_name    text;
begin
  -- Prefer full_name from OAuth metadata, fall back to email prefix
  v_full_name := coalesce(
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'name',
    split_part(new.email, '@', 1)
  );

  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, v_full_name);

  insert into public.workspaces (owner_id, type, name)
  values (new.id, 'personal', 'My Notes')
  returning id into v_workspace_id;

  insert into public.workspace_members (workspace_id, user_id, role)
  values (v_workspace_id, new.id, 'owner');

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- Profile delete cleanup -----------------------------------------------------
-- When a profile is deleted (cascades from auth.users delete):
--   • Personal workspace is cascade-deleted
--   • Campaign workspaces persist; owner_id FK is already set null by the FK
-- This trigger exists so we have a clear, explicit deletion of the personal
-- workspace regardless of FK ordering.
create or replace function public.handle_profile_delete()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.workspaces
  where owner_id = old.id
    and type = 'personal';

  return old;
end;
$$;

create trigger on_profile_deleted
  before delete on public.profiles
  for each row execute function public.handle_profile_delete();


-- Workspace type immutability ------------------------------------------------
create or replace function public.prevent_workspace_type_change()
returns trigger
language plpgsql
as $$
begin
  if new.type <> old.type then
    raise exception 'workspace.type is immutable';
  end if;
  return new;
end;
$$;

create trigger workspaces_immutable_type
  before update on public.workspaces
  for each row execute function public.prevent_workspace_type_change();


-- Single DM per campaign workspace -------------------------------------------
-- When a member is assigned the 'dm' role, any existing dm in that workspace
-- is demoted to 'player' first.
create or replace function public.enforce_single_dm()
returns trigger
language plpgsql
as $$
begin
  if new.role = 'dm' then
    update public.workspace_members
    set role = 'player'
    where workspace_id = new.workspace_id
      and role = 'dm'
      and user_id <> new.user_id;
  end if;
  return new;
end;
$$;

create trigger workspace_members_single_dm
  before insert or update on public.workspace_members
  for each row execute function public.enforce_single_dm();


-- =============================================================================
-- INVITE REDEMPTION FUNCTION
-- =============================================================================
-- Security definer so it can write to workspace_members and invites
-- atomically without the caller needing broad INSERT permissions.
create or replace function public.redeem_invite(p_token uuid)
returns uuid  -- returns workspace_id on success
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invite    public.invites%rowtype;
  v_ws_type   text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if not public.is_approved() then
    raise exception 'Account not approved';
  end if;

  -- Lock the invite row to prevent double-redemption under concurrent requests
  select * into v_invite
  from public.invites
  where token    = p_token
    and used_at  is null
    and expires_at > now()
  for update;

  if not found then
    raise exception 'Invalid or expired invite token';
  end if;

  select type into v_ws_type
  from public.workspaces
  where id = v_invite.workspace_id;

  if v_ws_type <> 'campaign' then
    raise exception 'Invite target is not a campaign workspace';
  end if;

  -- Add user as player; silently ignore if already a member
  insert into public.workspace_members (workspace_id, user_id, role)
  values (v_invite.workspace_id, auth.uid(), 'player')
  on conflict (workspace_id, user_id) do nothing;

  update public.invites
  set used_at = now()
  where id = v_invite.id;

  return v_invite.workspace_id;
end;
$$;


-- =============================================================================
-- ROW LEVEL SECURITY — enable on all tables
-- =============================================================================

alter table public.profiles          enable row level security;
alter table public.workspaces        enable row level security;
alter table public.workspace_members enable row level security;
alter table public.notes             enable row level security;
alter table public.note_links        enable row level security;
alter table public.tags              enable row level security;
alter table public.invites           enable row level security;


-- =============================================================================
-- RLS POLICIES
-- =============================================================================
-- Approval gate: every policy that accesses data (except own-profile reads,
-- which are needed for the middleware approval check) requires is_approved().
--
-- All membership checks go through security-definer helpers to avoid the
-- infinite-recursion trap of querying workspace_members from within its
-- own RLS policy.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------

-- Own profile is always visible — needed by middleware before approval check
create policy "profiles: own select"
  on public.profiles for select
  using (id = auth.uid());

-- Approved users may read profiles of people in any shared workspace
-- (needed for presence bar, member lists)
create policy "profiles: co-member select"
  on public.profiles for select
  using (
    public.is_approved()
    and exists (
      select 1
      from public.workspace_members m1
      join public.workspace_members m2 on m1.workspace_id = m2.workspace_id
      where m1.user_id = auth.uid()
        and m2.user_id = profiles.id
    )
  );

-- Users may update their own non-sensitive fields (full_name etc.)
-- approved can only be changed via service role (admin)
create policy "profiles: own update"
  on public.profiles for update
  using  (id = auth.uid())
  with check (id = auth.uid());


-- ---------------------------------------------------------------------------
-- workspaces
-- ---------------------------------------------------------------------------

create policy "workspaces: member select"
  on public.workspaces for select
  using (
    public.is_approved()
    and public.is_workspace_member(id)
  );

-- Users may only create campaign workspaces; personal is created by trigger
create policy "workspaces: approved create campaign"
  on public.workspaces for insert
  with check (
    public.is_approved()
    and auth.uid() = owner_id
    and type = 'campaign'
  );

-- Only the owner may rename their workspace (type is guarded by trigger)
create policy "workspaces: owner update"
  on public.workspaces for update
  using (
    public.is_approved()
    and owner_id = auth.uid()
  )
  with check (owner_id = auth.uid());

-- Owners may delete campaign workspaces; personal workspace deletion is
-- handled by the profile-delete trigger
create policy "workspaces: owner delete campaign"
  on public.workspaces for delete
  using (
    public.is_approved()
    and owner_id = auth.uid()
    and type = 'campaign'
  );


-- ---------------------------------------------------------------------------
-- workspace_members
-- ---------------------------------------------------------------------------

create policy "workspace_members: member select"
  on public.workspace_members for select
  using (
    public.is_approved()
    and public.is_workspace_member(workspace_id)
  );

-- Only owner/dm may add members; personal workspaces may not have members added
create policy "workspace_members: owner/dm insert"
  on public.workspace_members for insert
  with check (
    public.is_approved()
    and (select type from public.workspaces where id = workspace_id) = 'campaign'
    and public.workspace_role(workspace_id) in ('owner', 'dm')
  );

-- Only owner may reassign roles; owner cannot demote themselves
create policy "workspace_members: owner update role"
  on public.workspace_members for update
  using (
    public.is_approved()
    and public.workspace_role(workspace_id) = 'owner'
  )
  with check (
    -- Prevent the owner from changing their own role via this path
    not (user_id = (select owner_id from public.workspaces where id = workspace_id)
         and role <> 'owner')
  );

-- Members may leave; owner may remove any member except themselves
create policy "workspace_members: leave or owner kick"
  on public.workspace_members for delete
  using (
    public.is_approved()
    and (
      -- Any member can remove themselves (leave)
      user_id = auth.uid()
      -- Owner can remove others
      or public.workspace_role(workspace_id) = 'owner'
    )
    -- Owner cannot remove their own membership via this policy
    and not (
      user_id = auth.uid()
      and public.workspace_role(workspace_id) = 'owner'
    )
  );


-- ---------------------------------------------------------------------------
-- notes
-- ---------------------------------------------------------------------------
-- dm_only notes require role 'dm' or 'owner'; all other notes require membership.

create policy "notes: member select"
  on public.notes for select
  using (
    public.is_approved()
    and public.is_workspace_member(workspace_id)
    and (
      not dm_only
      or public.workspace_role(workspace_id) in ('owner', 'dm')
    )
  );

create policy "notes: member insert"
  on public.notes for insert
  with check (
    public.is_approved()
    and public.is_workspace_member(workspace_id)
    and (
      not dm_only
      or public.workspace_role(workspace_id) in ('owner', 'dm')
    )
  );

create policy "notes: member update"
  on public.notes for update
  using (
    public.is_approved()
    and public.is_workspace_member(workspace_id)
    and (
      not dm_only
      or public.workspace_role(workspace_id) in ('owner', 'dm')
    )
  )
  with check (
    public.is_workspace_member(workspace_id)
    and (
      not dm_only
      or public.workspace_role(workspace_id) in ('owner', 'dm')
    )
  );

create policy "notes: member delete"
  on public.notes for delete
  using (
    public.is_approved()
    and public.is_workspace_member(workspace_id)
    and (
      not dm_only
      or public.workspace_role(workspace_id) in ('owner', 'dm')
    )
  );


-- ---------------------------------------------------------------------------
-- note_links — inherit access from source note
-- ---------------------------------------------------------------------------

create policy "note_links: source note access select"
  on public.note_links for select
  using (
    public.is_approved()
    and exists (
      select 1
      from public.notes n
      join public.workspace_members wm on wm.workspace_id = n.workspace_id
      where n.id = note_links.source_id
        and wm.user_id = auth.uid()
        and (not n.dm_only or public.workspace_role(n.workspace_id) in ('owner', 'dm'))
    )
  );

create policy "note_links: source note access insert"
  on public.note_links for insert
  with check (
    public.is_approved()
    and exists (
      select 1
      from public.notes n
      join public.workspace_members wm on wm.workspace_id = n.workspace_id
      where n.id = note_links.source_id
        and wm.user_id = auth.uid()
        and (not n.dm_only or public.workspace_role(n.workspace_id) in ('owner', 'dm'))
    )
  );

create policy "note_links: source note access delete"
  on public.note_links for delete
  using (
    public.is_approved()
    and exists (
      select 1
      from public.notes n
      join public.workspace_members wm on wm.workspace_id = n.workspace_id
      where n.id = note_links.source_id
        and wm.user_id = auth.uid()
        and (not n.dm_only or public.workspace_role(n.workspace_id) in ('owner', 'dm'))
    )
  );


-- ---------------------------------------------------------------------------
-- tags — inherit access from parent note
-- ---------------------------------------------------------------------------

create policy "tags: note access select"
  on public.tags for select
  using (
    public.is_approved()
    and exists (
      select 1
      from public.notes n
      join public.workspace_members wm on wm.workspace_id = n.workspace_id
      where n.id = tags.note_id
        and wm.user_id = auth.uid()
        and (not n.dm_only or public.workspace_role(n.workspace_id) in ('owner', 'dm'))
    )
  );

create policy "tags: note access insert"
  on public.tags for insert
  with check (
    public.is_approved()
    and exists (
      select 1
      from public.notes n
      join public.workspace_members wm on wm.workspace_id = n.workspace_id
      where n.id = tags.note_id
        and wm.user_id = auth.uid()
        and (not n.dm_only or public.workspace_role(n.workspace_id) in ('owner', 'dm'))
    )
  );

create policy "tags: note access delete"
  on public.tags for delete
  using (
    public.is_approved()
    and exists (
      select 1
      from public.notes n
      join public.workspace_members wm on wm.workspace_id = n.workspace_id
      where n.id = tags.note_id
        and wm.user_id = auth.uid()
        and (not n.dm_only or public.workspace_role(n.workspace_id) in ('owner', 'dm'))
    )
  );


-- ---------------------------------------------------------------------------
-- invites
-- ---------------------------------------------------------------------------

-- Owner/dm can manage and view all invites for their workspace
create policy "invites: owner/dm select"
  on public.invites for select
  using (
    public.is_approved()
    and public.workspace_role(workspace_id) in ('owner', 'dm')
  );

-- Any approved user can read a pending invite by implicit token knowledge
-- (needed to render the /invite/[token] page before calling redeem_invite)
create policy "invites: approved read pending"
  on public.invites for select
  using (
    public.is_approved()
    and used_at is null
    and expires_at > now()
  );

create policy "invites: owner/dm insert"
  on public.invites for insert
  with check (
    public.is_approved()
    and public.workspace_role(workspace_id) in ('owner', 'dm')
    and created_by = auth.uid()
    -- 48-hour window enforced here; app layer sets expires_at
    and expires_at <= now() + interval '48 hours'
  );

create policy "invites: owner/dm delete"
  on public.invites for delete
  using (
    public.is_approved()
    and public.workspace_role(workspace_id) in ('owner', 'dm')
  );


-- =============================================================================
-- STORAGE
-- =============================================================================
-- Bucket: 'workspaces'  (private)
-- Path layout inside bucket: {workspace_id}/images/{filename}
--
-- The bucket insert below is idempotent. If you manage buckets via the
-- Supabase dashboard instead, remove it.
-- =============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'workspaces',
  'workspaces',
  false,
  10485760, -- 10 MB per file
  array['image/jpeg','image/png','image/gif','image/webp','image/svg+xml']
)
on conflict (id) do nothing;


-- Storage object policies ----------------------------------------------------
-- (storage.objects RLS must be enabled — it is by default in Supabase)

-- Workspace members may download images from their workspace
create policy "storage workspaces: member read"
  on storage.objects for select
  using (
    bucket_id = 'workspaces'
    and public.is_approved()
    and public.is_workspace_member(
      (storage.foldername(name))[1]::uuid
    )
  );

-- Workspace members may upload images to their workspace path
create policy "storage workspaces: member upload"
  on storage.objects for insert
  with check (
    bucket_id = 'workspaces'
    and public.is_approved()
    and public.is_workspace_member(
      (storage.foldername(name))[1]::uuid
    )
  );

-- Members may overwrite their own uploads; owner/dm may overwrite any
create policy "storage workspaces: member update"
  on storage.objects for update
  using (
    bucket_id = 'workspaces'
    and public.is_approved()
    and public.is_workspace_member(
      (storage.foldername(name))[1]::uuid
    )
  );

-- Only owner/dm may delete objects (e.g. admin workspace delete cascade)
create policy "storage workspaces: owner/dm delete"
  on storage.objects for delete
  using (
    bucket_id = 'workspaces'
    and public.is_approved()
    and public.workspace_role(
      (storage.foldername(name))[1]::uuid
    ) in ('owner', 'dm')
  );
